steps:
  - name: build
    image: maven:3-jdk-11
    commands:
      - mvn -B -DskipTests clean install
      - mvn test -B
    volumes:
      - /home/docker/woodpecker/files/m2:/root/.m2

  - name: archive-artifact
    image: alpine:latest
    commands:
      - mkdir -p /builds/ESRPatchJava
      - cp target/ESRPatchJava-*[0-9].jar /builds/ESRPatchJava/
    volumes:
      - /home/www/builds:/builds
